stages:
    - build
    - deploy
    
build-master:
    stage: build
    tags:
        - x86
    script:
        - cd python-openzwave:master
        - make build
    
build-master-rpi:
    stage: build
    tags:
        - rpi
    script:
        - cd rpi-python-openzwave:master
        - make build
        
deploy-master:
    stage: deploy
    tags:
        - x86
    script:
        - cd python-openzwave:master
        - make push
        
deploy-master-rpi:
    stage: deploy
    tags:
        - rpi
    script:
        - cd rpi-python-openzwave:master
        - make push
        
